### ISSUE TITLE
feature request: add option to get subdirectory in repo with GIT_SYNC_ONE_TIME 

### ISSUE THREAD

**Issue by sean-krail** [kubernetes/git-sync#233]
I'm looking for a way to get a single directory (3 levels deep) within my git repository when using the `GIT_SYNC_ONE_TIME` flag in an init container. Right now my workaround is to use a second init container that modifies the `emptyDir` volume to go 3 directories lower or use `volumeMounts.subPath` in the container to only mount the desired directory.

Some background: it's a git ops repository that holds configuration data (44MB) for various applications and environments in a structure of `<kubernetes_cluster>/<kubernetes_namespace>/<application>/<configuration_data>`.

**Comment by stp-ip** [comment]
Prior to version 2.19 Git would always get the full repository so having a subdirectory setting doesn't seem to add much besides not having to use subPath in your case.

The only possibility might be to work towards general "git clone --filter" support also called sparse checkout. This is only available in 2.19 (git client), 2.20 (git server) and not at all on Github or other hosted services. Gitlab does have experimental support.

So a PR to add sparse checkout support might be ok, once the git version in our used Debian is at 2.19 and support from platforms is more mature.

**Comment by thockin** [comment]
Dup of #54 

What you are doing is the best you can get today.  subPath is nice but will not update when the upstream changes (because subPath uses a bind mount, which derefs the symlink, pinning you at one rev).

I am looking for ways to make checkouts more efficient overall, but less-than-whole-repo use-cases seem poorly supported by git overall.
