### ISSUE TITLE
Support using custom ca(self-signed) for interacting with git

### ISSUE THREAD

**Issue by onesolpark** [kubernetes/git-sync#235]
There are some usecases where git is using a self-signed certificate
and the git command supports specifying the cert file to use.

Support using self-singed cert for interacting with git
`git config --global http.sslCAInfo /path/to/cert/file`

or support skip tlsVerify in git (this may be not secure)
`git config --global http.sslVerify false`

**Comment by thockin** [comment]
I could maybe see a way to pass git configs in, rather than writing features to support all of these.

It's easier with flags than env vars, but something like:

```
--git-config "global:http.sslCAInfo:/path/to/cert/file"
```

If you specify it more than once, we should just accumulate them.  For env var I guess it would be something like "global:k1:v1,global:k2:v2".  We'd need to handle escaping properly (I don't know if ':' and ',' are ever allowed in keys, but they are in values.

I'm not sure if the first part is needed (or if we can just assume global always).

This should be a relatively easy change.  PRs welcome :)

**Comment by onesolpark** [comment]
/assign 
I'll work on a PR for this one

**Comment by dbrau** [comment]
Hi. Is there any further news on this topic? We would like to use that but need the ca configuration unfortunately. I would be very happy if this function would be integrated. =)  Thanks!

**Comment by thockin** [comment]
Hi, I have proposed #341 as a way to pass arbitrary args.
