### ISSUE TITLE
Default wait time of 0 second is too aggresive

### ISSUE THREAD

**Issue by killuazhu** [kubernetes/git-sync#244]
Relates to #243

The default wait time 0 is too aggressive. My team manages a Github Enterprise instance, we had a user who use the default value and cause 200 calls per second against his own repo.

As a default value, having wait time seems to be too aggressive.

@thockin suggested to create this issue and lower the wait to 1 second. From my point of view, anything longer than 0 second is better than what we have now.

**Comment by jacksontj** [comment]
@thockin I just ran into this issue today; we (apparently) became the most pulled github repo globally on accident >.<

So I'd agree that this should be some non-zero number by default (to avoid crushing the git repo) and I think its fine to leave the ability to set this to 0 in case people want that functionality.

**Comment by killuazhu** [comment]
Would love to see the change get merged soon. 😃

**Comment by thockin** [comment]
@jacksontj yikes!

I am afraid of merging this because of the breaking-change nature of it.  It really COULD break someone.  If I am being honest, I have a hard time seeing it happening (change from 0s to 1s) but it feels wrong for a point release.

@stp-ip What if we started a 3.2 series with this as the flagship change - "minor breaking" but API compatible?  What do you think?

**Comment by stp-ip** [comment]
@jacksontj congratulations on that achievement I guess :P

Same thinking that I assume it will most likely not break someone, but one never knows.

3.2 sounds like a reasonable balance.

**Comment by thockin** [comment]
Merged, will cut a 3.2.0 soon

**Comment by thockin** [comment]
Try k8s.gcr.io/git-sync/git-sync:v3.2.0
