### ISSUE TITLE
Host key verification failed

### ISSUE THREAD

**Issue by bialad** [kubernetes/git-sync#3]
> 2016/09/03 08:37:57 error syncing repo: error cloning repo "git clone --no-checkout -b master ssh://name@name.visualstudio.com:22/repo/_git/web /git": exit status 128: Cloning into '/git'...
> Host key verification failed.
> fatal: Could not read from remote repository.

> Please make sure you have the correct access rights
> and the repository exists.

I'm getting a host verification error, which I don't even see how it's possible with the ssh_wrapper. In kubernetes I use the demo yaml-files and a secret.yaml as follows:

> apiVersion: v1
> kind: Secret
> metadata:
>   name: git-creds
>   namespace: zeptio
> type: Opaque
> data:
>   ssh: "base64-private-key"

This is the command I run on my local host for testing this out:

`docker run --rm -e GIT_SYNC_REPO="ssh://name@name.visualstudio.com:22/repo/_git/web" -e GIT_SYNC_SSH=true -v /home/name/web:/git -v /home/name/git-secret:/etc/git-secret gcr.io/google_containers/git-sync`

Where /home/name/git-secret contains my non-base64 coded private key.

If I run 

`git clone --no-checkout -b master ssh://name@name.visualstudio.com:22/repo/_git/web /git`

on my local machine, using the ssh key in /home/name/git-secret, everything works fine.

Any idea what could be happening here?

**Comment by stp-ip** [comment]
As far as I can tell, the current image tagged at gcr.io/google_containers/git-sync is not using the ssh-wrapper.
In addition to that. I don't see that the git-sync image published is anything like the current dockerfile.
The pushed image is from something like mid 2015.

Any chance new images might be pushed soonish? @thockin 
As you had the plan to make this the new default sidecar instead of using gitRepo, I would prefer not building this myself, but give me a hint that you are busy and I'll build images for our use-cases.

**Comment by thockin** [comment]
I'll push a new one and tag it 2.0.0.  I am on a slow link now.
