### ISSUE TITLE
Syncing multiple repositories

### ISSUE THREAD

**Issue by ClassyLion** [kubernetes/git-sync#352]
Hello.
I have a use case, where I would require to sync 2 repositories to a kubernetes pod. Currently one repository is being synced and I wanted to know if it is possible to add sync for another repository. If yes, then what would be the correct way?

I was not sure if it was a good idea to add git_sync_repo, etc. for the second time in the configuration and I couldn't fidn information on how to do it properly.

**Comment by stp-ip** [comment]
With git-sync itself one can't sync multiple repositories.
It would boil down to either starting 2 git-sync binaries inside one container or my personal recommendation use separate git-sync containers. That would also split up logging, error reporting to each repository.

Let me know, if that doesn't solve the issue.

**Comment by ClassyLion** [comment]
How do you realise these two strategies? Maybe a guide available or any tips? Any kind of help will be appreciated.

**Comment by stp-ip** [comment]
https://github.com/kubernetes/git-sync/blob/release-3.x/docs/kubernetes.md

And instead of having a single git-sync container writing to the emptyDir backed directory one would create and start a second one, which could use the the same emptyDir and another subdirectory or use its own emptyDir as well.
