### ISSUE TITLE
Keep [N] Old Worktrees

### ISSUE THREAD

**Issue by doddsiedodds** [kubernetes/git-sync#692]
Hey,

We're using git-sync in a variety of application deployments (for example, apache airflow for DAG code) and find that when a workdir is deleted from under the application's feet, it tends to not handle it gracefully.

I was thinking of forking and adding support for either 1) keeping N previous worktrees or 2) keep all previous worktrees. 2 is significantly easier to implement I expect, I would then write application code to clean-up workdirs over a certain age.

Is this something you've considered before or, if I was to do the work, something you'd consider as a feature?

Cheers,
Matt

**Comment by thockin** [comment]
I am in the middle of a major overhaul for V4, but it doesn't change this
particular behavior (it does change a lot of the code, though!).

I have never considered this, no. Not that I am, per se, against it but I
don't think anyone has asked for it.

Are you using the worktree as the working directory for you app?  That
could be a problem, for sure.  Or are you just not happy with doing
file-accesses across two different SHAs, even if the switchover is atomic
and otherwise undetectable?

Part of the new v4 work is a focus on efficiency - for example making
--depth default to 1.  Keeping _all_ worktrees would change that a lot, but
not so bad if you are opting in to it.  Impl should be easy.

A FIFO of worktrees seems cute, but requires an index to track, which makes
it more complicated.  So unless that is ACTUALLY the needed behavior, I'd
avoid it.

Help me understand what the app is doing?

**Comment by doddsiedodds** [comment]
Exactly as described, the worktree is a working directory for the app.  As a concrete example, apache airflow loads a large set of python scripts containing DAG definitions from a git-synced directory, if the current tree symlink is flipped and the old folder is cleaned up while its going through this process it can cause errors.

Agreed re: FIFO being significantly more complicated to implement, it's not _needed_ per se, just that without it, we'd end up probably writing a garbage collection/housekeeping job to clean up old worktrees after some period of time. The reason I considered git-sync itself taking care of it via a FIFO queue was that I feel the expected pattern is that git-sync is the *only* thing managing the folders in the root checkout folder.

**Comment by thockin** [comment]
Does it need to be the working directory?  Can the app just refer to files by a fuller path?  That would trade this problem for a different one, in particular I could read file A from hash abc123 and file B from hash def456.

The problem with FIFO is that it just extends the problem from "delete now" to "delete later" without any indication of whether/when it is actually OK to do so.

Keeping all worktrees is disk-inefficient, for sure.

If it's not possible to not use it as CWD, how could we indicate "it's safe to clean up now"?

**Comment by doddsiedodds** [comment]
It could still introduce errors if, in your example file `A @ abc123` imported a specific function from file B that was removed in the subsequent commit `def456`.

Agree re problems with FIFO, ultimately we'd make a decision to clean up directories older than some reasonable length of time (i.e. we would expect all jobs using a specific hash to be done within 2 hours). Disk efficiency isn't a huge concern for us specifically and I'd definitely trade disk space for service continuity.

There's definitely many solutions to each specific application's failure modes around the directory being removed from underneath them but making a change along these lines in git-sync would mean we could hopefully solve them all once rather than once-per-app.

Thanks for all your commentary thus far, good to talk this out!

**Comment by thockin** [comment]
So what are the options?

1) do nothing - it's on the consumer to hold it properly

2) add FIFO(n) with a flag defining N.

3) add time based retention with a flag to define that time

4) add a way to signal "I am done with this" and make consumers notify
git-sync

5) auto detect if another PID is in the git for

6) ??

I would prefer not to do multiple of these, but I can see how they are all
imperfect.

**Comment by doddsiedodds** [comment]
I think 2) would be useful with the ordering determined by the commit hash order as shown by `git log` to determine oldest?
If that flag could accept a -1 argument to keep all old worktrees then people could also manage their own GC process against a git-synced directory to clean up old worktrees.

An errant thought: should the `N` someone specifies here be exactly the same as the `--depth` argument being passed to `git`?

3) would still need 2) I expect as you'd want to keep at least one previous version. 4) would be tricky to implement in all downstream apps I think. 5) Is an interesting idea but I have no idea how this mechanism would work and whether it would be appropriate here (looking as `lsof` output for a worktree?)

**Comment by thockin** [comment]
> should the N someone specifies here be exactly the same as the --depth argument

I don't think so - I think they feel similar but actually have no relationship to each other.  In v4 I'm going to propose that `--depth` default to 1 (I have a bunch of PRs pending and more in the queue :)

> 3) would still need 2) I expect as you'd want to keep at least one previous version

I don't think that's so clear.  The semantic of (2) is pretty obvious - keep the N most recent worktrees.  The semantic of (3) is fairly obvious, but not as much as (2) - keep old (non-current) wortrees for T time.  What isn't so clear is when clean up happens - do we evaluate the time at the very next syncloop (even if there's no upstream change) or only at the next upstream change?

Then we have to decide what happens if someone specifies both?  Or just declare that an error?  Do we even need both or could we get away with just (3)?  I think (3) alone is more useful than (2) alone - more predictable and can be set based on your workload's needs rather than the pace of commits to a repo.  

Can we simply use the timestamp on the worktree dir, with no extra metadata?  A quick test seems like yes.

So maybe the semantic is, when cleaning up, to only delete worktrees older than T time.  Simplest simplest is to only evaluate this when we do a new sync (IOW, if upstream never changes, we never clean up), but that's somewhat unsatisfying.  To do it more aggressively would mean running a cleanup pass every sync loop, which isn't SO bad, especially after all my v4 changes go in (https://github.com/kubernetes/git-sync/compare/master...thockin:git-sync:master is my working tree)

**Comment by thockin** [comment]
I'd be open a PoC PR to evaluate it - preferably built on top of the branch
I linked above (my "master", which I now realize I should make a diff
branch for, oops).

In particular I want to see the e2e tests that prove it works :)

**Comment by doddsiedodds** [comment]
Sure - i'll try take a look at this in the coming weeks, thanks for the guidance!

**Comment by thockin** [comment]
Circling back to open topics - any progress here?

**Comment by doddsiedodds** [comment]
No movement on this yet sorry! Still on my backlog to do, though
