### ISSUE TITLE
Git-sync fails with context deadline exceeded.

### ISSUE THREAD

**Issue by JustMaris** [kubernetes/git-sync#708]
My team uses git-sync to sync a git repository to Kubernetes, efs, for it to be used by Airflow. When git-sync gets deployed, the first sync usually succeeds, but some time after they start to fail.

Logs, that repeat on cycle, with each restart of the pod:
```shell
INFO: detected pid 1, running init handler
I0418 08:09:54.059208      12 main.go:401] "level"=0 "msg"="starting up" "pid"=12 "args"=["/git-sync"]
I0418 08:10:03.170088      12 main.go:1112] "level"=0 "msg"="update required" "rev"="HEAD" "local"="f6f...d9e" "remote"="72f...e8f"
I0418 08:10:03.170115      12 main.go:760] "level"=0 "msg"="syncing git" "rev"="HEAD" "hash"="72f...e8f"
I0418 08:10:50.950981      12 main.go:800] "level"=0 "msg"="adding worktree" "path"="/opt/company/dags/72f...e8f" "branch"="origin/master"
E0418 08:11:54.232253      12 main.go:547] "msg"="too many failures, aborting" "error"="Run(git reset --hard 72f...e8f): context deadline exceeded: { stdout: "", stderr: "Updating files:   2% (6/244)\rUpdating files:   2% (7/244)\rUpdating files:   3% (8/244)\rUpdating files:   4% (10/244)\rUpdating files:   5% (13/244)\rUpdating files:   6% (15/244)\rUpdating files:   6% (16/244)\rUpdating files:   7% (18/244)\rUpdating files:   8% (20/244)\rUpdating files:   9% (22/244)\rUpdating files:  10% (25/244)\rUpdating files:  11% (27/244)\rUpdating files:  11% (28/244)\rUpdating files:  12% (30/244)\rUpdating files:  13% (32/244)\rUpdating files:  13% (34/244)\rUpdating files:  14% (35/244)\rUpdating files:  15% (37/244)\rUpdating files:  15% (38/244)\rUpdating files:  15% (39/244)\rUpdating files:  16% (40/244)\rUpdating files:  16% (41/244)\rUpdating files:  17% (42/244)\rUpdating files:  18% (44/244)\rUpdating files:  18% (46/244)\rUpdating files:  19% (47/244)\rUpdating files:  19% (48/244)\rUpdating files:  20% (49/244)\rUpdating files:  20% (50/244)\rUpdating files:  20% (51/244)\rUpdating files:  21% (52/244)\rUpdating files:  21% (53/244)\rUpdating files:  22% (54/244)\rUpdating files:  22% (56/244)\rUpdating files:  23% (57/244)\rUpdating files:  24% (59/244)\rUpdating files:  25% (61/244)\rUpdating files:  25% (62/244)\rUpdating files:  25% (63/244)\rUpdating files:  26% (64/244)\rUpdating files:  26% (65/244)\rUpdating files:  27% (66/244)\rUpdating files:  27% (67/244)\rUpdating files:  27% (68/244)\rUpdating files:  28% (69/244)\rUpdating files:  28% (70/244)\rUpdating files:  29% (71/244)\rUpdating files:  29% (73/244)\rUpdating files:  30% (74/244)\rUpdating files:  31% (76/244)\rUpdating files:  31% (77/244)\rUpdating files:  32% (79/244)\rUpdating files:  32% (80/244)\rUpdating files:  33% (81/244)\rUpdating files:  34% (83/244)\rUpdating files:  34% (84/244)\rUpdating files:  35% (86/244)\rUpdating files:  36% (88/244)\rUpdating files:  36% (90/244)\rUpdating files:  37% (91/244)\rUpdating files:  37% (92/244)\rUpdating files:  38% (93/244)\rUpdating files:  38% (94/244)\rUpdating files:  38% (95/244)" }" "failCount"=1
``` 
The percentage it reaches changes from run to run.

I have tried setting different git_sync parameters and increasing memory for the pod, but the result is the same.
Current parameters:
```shell
  GIT_SYNC_SSH: "True"
  GIT_SYNC_DEPTH: "1"
  GIT_SYNC_GIT_GC: "auto"
  GIT_SYNC_SUBMODULES: "off"
  GIT_SYNC_KNOWN_HOSTS: "False"
  GIT_SYNC_SYNC_TIMEOUT: "600"
``` 

Previously some other errors appeared, but with these parameters, they are solved, now only this one is left.

**Comment by thockin** [comment]
That log shows 64 seconds from "adding worktree" to "too many failures".  The main thing that happens after "adding worktree" but before the next log line is `git reset`.

What version of git-sync is this?

Is it a very large repo or a very slow machine?

Can you re-run with `-v 6` and paste those logs?

Are you sure that setting the `--timeout` ($GIT_SYNC_TIMEOUT - not GIT_SYNC_SYNC_TIMEOUT as you listed) doesn't fix this?  It sure smells of a huge repo to me.

**Comment by JustMaris** [comment]
This is the latest version, 3.6.5. The repository on my local computer takes up around 14.4MiB. It has around 3.2k commits, but I have set the depth to 1. The machine itself is a container in Kubernetes. According to resource usage metrics, it shouldn't be slow, as it has been granted more than enough resources.

How can I set log verbosity if git-sync is run as a container in Kubernetes, not as a command?
I have now changed the setting to timeout, instead of sync_timeout. I got confused with the development readme, which said that synt_timeout obsoleted timeout, but then I looked at 3.x readme.

**Comment by thockin** [comment]
> How can I set log verbosity if git-sync is run as a container in Kubernetes, not as a command?

The same as you would set any commandline argument:

In your Deployment/Job/StafulSet/whatever, there's a pod spec, it will already have something like:

```
spec:
  containers:
  - name: gitsync
    image: registry.k8s.io/git-sync/git-sync:v3.6.5
```

You can add args to the container:

```
    args:
      - -v=6
```

**Comment by cnkumar20** [comment]
is this still open?

I am getting following with 3.6.1 image , verbose =6, I even tried setting timeout to 2000 and default.

-bash-4.2$ klo git-sync-example-8b8c495c6-plwjh
INFO: detected pid 1, running init handler
I0426 04:12:36.856180      11 main.go:389] "level"=0 "msg"="starting up" "pid"=11 "args"=["/git-sync","--repo=ssh://git@git.*******.net:7999/*****/****-dags.git","--branch=dev","--root=/gitsync1","--ssh","-v=6"]
I0426 04:12:36.856265      11 cmd.go:48] "level"=5 "msg"="running command" "cwd"="" "cmd"="git config --global gc.autoDetach false"
I0426 04:12:36.860120      11 cmd.go:72] "level"=6 "msg"="command result" "stdout"="" "stderr"=""
I0426 04:12:36.860182      11 cmd.go:48] "level"=5 "msg"="running command" "cwd"="" "cmd"="git config --global gc.pruneExpire now"
I0426 04:12:36.862846      11 cmd.go:72] "level"=6 "msg"="command result" "stdout"="" "stderr"=""
I0426 04:12:36.862877      11 cmd.go:48] "level"=5 "msg"="running command" "cwd"="" "cmd"="git config --global credential.helper "cache --timeout 3600""
I0426 04:12:36.865287      11 cmd.go:72] "level"=6 "msg"="command result" "stdout"="" "stderr"=""
I0426 04:12:36.865332      11 main.go:1123] "level"=1 "msg"="setting up git SSH credentials"
I0426 04:12:36.865387      11 main.go:527] "level"=1 "msg"="syncing repo"
I0426 04:12:36.865674      11 main.go:934] "level"=0 "msg"="cloning repo" "origin"="ssh://git@git.******.net:7999/*****/****-dags.git" "path"="/gitsync1"
I0426 04:12:36.865707      11 cmd.go:48] "level"=5 "msg"="running command" "cwd"="" "cmd"="git clone -v --no-checkout -b dev ssh://git@git.*****.net:7999/****/****-dags.git /gitsync1"
I0426 04:12:36.868436      11 main.go:940] "level"=0 "msg"="git root exists and is not empty (previous crash?), cleaning up" "path"="/gitsync1"
I0426 04:12:36.868878      11 main.go:611] "level"=2 "msg"="removing path recursively" "path"="/gitsync1/.git" "isDir"=true
I0426 04:12:36.933464      11 cmd.go:48] "level"=5 "msg"="running command" "cwd"="" "cmd"="git clone -v --no-checkout -b dev ssh://git@git.******.net:7999/****/***-dags.git /gitsync1"
E0426 04:15:19.733571      11 main.go:535] "msg"="too many failures, aborting" "error"="Run(git clone -v --no-checkout -b dev ssh://git@git.*******.net:7999/****/***-dags.git /gitsync1): context deadline exceeded: { stdout: "", stderr: "Cloning into '/gitsync1'...\nFailed to add the RSA host key for IP address '[*.*.*.*]:7999' to the list of known hosts (/etc/git-secret/known_hosts).\r\nfatal: early EOF" }" "failCount"=1
-bash-4.2$ ls

**Comment by thockin** [comment]
OK.  Then, if you set the timeout to 1000 - what do the logs say?

**Comment by cnkumar20** [comment]
env:
            - name: GIT_SYNC_SYNC_TIMEOUT
              value: "2000"


I have this following in Kubernetes file. it failed

**Comment by JustMaris** [comment]
Try GIT_SYNC_TIMEOUT as a variable. Changing from sync timeout to timeout
fixed my problem and now I haven't had issues for a couple of days at least.

**Comment by thockin** [comment]
This is why flags are better than env vars - I can yell at you when you give me a bad flag, but bad env vars are silently ignore.

**Comment by cnkumar20** [comment]
ok I tried with flag timeout=1000, It failed with same error , since I ran this as a Kubernetes deployment job after failure, the pod restarted and git-sync ran fine.


-bash-4.2$ klo git-sync-example-77b584c6dd-8rt7g
INFO: detected pid 1, running init handler
I0426 17:35:23.190818      10 main.go:389] "level"=0 "msg"="starting up" "pid"=10 "args"=**["/git-sync","--repo=ssh://git@git.***.net:7999/cadence/dpl-dags.git","--branch=dev","--root=/gitsync","--ssh","-v=6","--one-time","--timeout=2000"]**
I0426 17:35:23.190932      10 cmd.go:48] "level"=5 "msg"="running command" "cwd"="" "cmd"="git config --global gc.autoDetach false"
I0426 17:35:23.194482      10 cmd.go:72] "level"=6 "msg"="command result" "stdout"="" "stderr"=""
I0426 17:35:23.194510      10 cmd.go:48] "level"=5 "msg"="running command" "cwd"="" "cmd"="git config --global gc.pruneExpire now"
I0426 17:35:23.197102      10 cmd.go:72] "level"=6 "msg"="command result" "stdout"="" "stderr"=""
I0426 17:35:23.197136      10 cmd.go:48] "level"=5 "msg"="running command" "cwd"="" "cmd"="git config --global credential.helper "cache --timeout 3600""
I0426 17:35:23.199654      10 cmd.go:72] "level"=6 "msg"="command result" "stdout"="" "stderr"=""
I0426 17:35:23.199689      10 main.go:1123] "level"=1 "msg"="setting up git SSH credentials"
I0426 17:35:23.199743      10 main.go:527] "level"=1 "msg"="syncing repo"
I0426 17:35:23.200200      10 main.go:934] "level"=0 "msg"="cloning repo" "origin"="ssh://git@git.cnvrmedia.net:7999/cadence/dpl-dags.git" "path"="/gitsync"
I0426 17:35:23.200228      10 cmd.go:48] "level"=5 "msg"="running command" "cwd"="" "cmd"="git clone -v --no-checkout -b dev ssh://git@git.***.net:7999/cadence/dpl-dags.git /gitsync"
I0426 17:38:11.505634      10 cmd.go:72] "level"=6 "msg"="command result" "stdout"="" "stderr"="Cloning into '/gitsync'...
**Failed to add the RSA host key for IP address '[********]:7999' to the list of known hosts (/etc/git-secret/known_hosts)."
I0426 17:38:11.505706      10 cmd.go:48] "level"=5 "msg"="running command" "cwd"="/gitsync" "cmd"="git rev-parse HEAD"**
I0426 17:38:11.512294      10 cmd.go:72] "level"=6 "msg"="command result" "stdout"="cd5bee11acdc358a4d0fcd962b59de4fac4c8961" "stderr"=""
I0426 17:38:11.512334      10 main.go:748] "level"=0 "msg"="syncing git" "rev"="HEAD" "hash"="cd5bee11acdc358a4d0fcd962b59de4fac4c8961"
I0426 17:38:11.512364      10 cmd.go:48] "level"=5 "msg"="running command" "cwd"="/gitsync" "cmd"="git fetch -f --tags ssh://git@git.cnvrmedia.net:7999/cadence/dpl-dags.git dev"
I0426 17:38:12.327569      10 cmd.go:72] "level"=6 "msg"="command result" "stdout"="" "stderr"="Failed to add the RSA host key for IP address '[********]:7999' to the list of known hosts (/etc/git-secret/known_hosts).
From ssh://git.******.net:7999/cadence/dpl-dags
 * branch              dev        -> FETCH_HEAD"
I0426 17:38:12.327612      10 cmd.go:48] "level"=5 "msg"="running command" "cwd"="/gitsync" "cmd"="git cat-file -t cd5bee11acdc358a4d0fcd962b59de4fac4c8961"
I0426 17:38:12.333598      10 cmd.go:72] "level"=6 "msg"="command result" "stdout"="commit" "stderr"=""
I0426 17:38:12.333634      10 cmd.go:48] "level"=5 "msg"="running command" "cwd"="/gitsync" "cmd"="git rev-parse cd5bee11acdc358a4d0fcd962b59de4fac4c8961"
I0426 17:38:12.337971      10 cmd.go:72] "level"=6 "msg"="command result" "stdout"="cd5bee11acdc358a4d0fcd962b59de4fac4c8961" "stderr"=""
I0426 17:38:12.338000      10 main.go:737] "level"=1 "msg"="removing worktree" "path"="/gitsync/cd5bee11acdc358a4d0fcd962b59de4fac4c8961"
I0426 17:38:12.338349      10 cmd.go:48] "level"=5 "msg"="running command" "cwd"="/gitsync" "cmd"="git worktree prune"
I0426 17:38:12.342011      10 cmd.go:72] "level"=6 "msg"="command result" "stdout"="" "stderr"=""
I0426 17:38:12.342049      10 cmd.go:48] "level"=5 "msg"="running command" "cwd"="/gitsync" "cmd"="git worktree add --detach /gitsync/cd5bee11acdc358a4d0fcd962b59de4fac4c8961 cd5bee11acdc358a4d0fcd962b59de4fac4c8961 --no-checkout"
I0426 17:38:12.365619      10 cmd.go:72] "level"=6 "msg"="command result" "stdout"="Preparing worktree (detached HEAD cd5bee11)" "stderr"=""
I0426 17:38:12.365660      10 main.go:783] "level"=0 "msg"="adding worktree" "path"="/gitsync/cd5bee11acdc358a4d0fcd962b59de4fac4c8961" "branch"="origin/dev"
I0426 17:38:12.366580      10 cmd.go:48] "level"=5 "msg"="running command" "cwd"="/gitsync/cd5bee11acdc358a4d0fcd962b59de4fac4c8961" "cmd"="git reset --hard cd5bee11acdc358a4d0fcd962b59de4fac4c8961"
I0426 17:38:12.789130      10 cmd.go:72] "level"=6 "msg"="command result" "stdout"="HEAD is now at cd5bee11 Increasing the Offset as part of dual Publish testing" "stderr"=""
I0426 17:38:12.789167      10 main.go:844] "level"=0 "msg"="reset worktree to hash" "path"="/gitsync/cd5bee11acdc358a4d0fcd962b59de4fac4c8961" "hash"="cd5bee11acdc358a4d0fcd962b59de4fac4c8961"
I0426 17:38:12.789199      10 main.go:849] "level"=0 "msg"="updating submodules"

**Comment by thockin** [comment]
This log indicates success - so what's the problem?

In particular:

```
I0426 17:35:23.200228      10 cmd.go:48] "level"=5 "msg"="running command" "cwd"="" "cmd"="git clone -v --no-checkout -b dev ssh://git@git.***.net:7999/cadence/dpl-dags.git /gitsync"
I0426 17:38:11.505634      10 cmd.go:72] "level"=6 "msg"="command result" "stdout"="" "stderr"="Cloning into '/gitsync'...
```

The clone took just under 3 full minutes to run.

**Comment by cnkumar20** [comment]
so with timeout set to 1000, what I see is it failed in first try for git clone with same error and the pod went to CrashLoopBackOff, and after restart pulled succesffully as you see in continuous log  and the pod is still in CrashLoopBackOff.

git-sync-example-77b584c6dd-nl6qp                                 0/1     CrashLoopBackOff   3 (41s ago)    4m14s

**Comment by thockin** [comment]
I'm sorry, I don't quite understand:

> with timeout set to 1000, what I see is it failed in first try for git clone with same error and the pod went to CrashLoopBackOff

And each failed attempt failed with the same errors?  Where is the `-v 6` log with `--timeout` set?  I see a log without it set and I see a successful log

> after restart pulled succesffully

What does "restart" mean here?  CrashLoop is restarting

> and the pod is still in CrashLoopBackOff

Well, you are running with `--one-time` which exits after running, which Kubernetes will then try to restart for you, so you *are* in a crash loop (you failed successfully :)

**Comment by thockin** [comment]
Reopen if this persists

**Comment by cnkumar20** [comment]
Adding timeout worked for us , which makes me think it is a latency issue. Thank you.

> I'm sorry, I don't quite understand:
> 
> > with timeout set to 1000, what I see is it failed in first try for git clone with same error and the pod went to CrashLoopBackOff
> 
> And each failed attempt failed with the same errors? Where is the `-v 6` log with `--timeout` set? I see a log without it set and I see a successful log
> 
> > after restart pulled succesffully
> 
> What does "restart" mean here? CrashLoop is restarting
> 
> > and the pod is still in CrashLoopBackOff
> 
> Well, you are running with `--one-time` which exits after running, which Kubernetes will then try to restart for you, so you _are_ in a crash loop (you failed successfully :)

in the log I shared I have the -v=6 and --timeout=2000 (line number 3), error message is not relatable to the actual issue.
