### ISSUE TITLE
Curious about real example raising race condition when using v3

### ISSUE THREAD

**Issue by hans818Tossbank** [kubernetes/git-sync#880]
Hi, I’m using git sync components at airflow cluster in kubernetes.

We need to consider of operating git-sync components with multiple replicas because of HA.

And I found really great [document](https://github.com/kubernetes/git-sync/blob/master/v3-to-v4.md) for explaining about how does git-sync work.

But ... I can not come up with real example when using git sync in airflow cluster, why does v3 mechanism raise race condition and make some bugs related to back to back runs of git sync.

Could you please real example when does v3 make race condition in airflow and why is v4 secure when using `git init + git fetch <remote> <refs>` ?

**Comment by thockin** [comment]
The race was like this:

* Running git-sync with a low `--depth` (e.g. `--depth=1`)
* Git-sync resolves the branch to a SHA (e.g. AAAAA) and syncs
* User pushes an update to git repo, SHA is BBBBB
* Git sync wakes up and sees that the branch resolves to SHA BBBBB
* User pushes an update to git repo, SHA is CCCCC
* Git-sync `fetch`es the branch, gets CCCCC
* Git-sync tries to `reset` to BBBBB
* BBBBB is not in the local repo because depth was 1

In v4, we would  `fetch` the branch and resolve it to CCCCC in one step.

Hope that helps!
