### ISSUE TITLE
How to use GITSYNC_SYNC_ON_SIGNAL parameter through helm in k8s?

### ISSUE THREAD

**Issue by liangpengfei** [kubernetes/git-sync#911]
I want to notify git-sync to trigger code synchronization in k8s, but I don't know how to send signal to k8s pod gracefully. Can someone help me? Thank you very much.

**Comment by thockin** [comment]
Can you expand a little more on what you are trying to achieve?  You are describing it as "on signal", but that's not how this tool currently works. Help me understand why polling loop, which is what we have, isn't sufficient for this use case?  I'm not saying your requirement is wrong, I just want to understand it. It has come up a few times over the years, but not that much, and everybody who has brought it up has found other solutions. 

How does the actor who is sending the "notification" know when to send it?  Is the git-sync container running all the time, or is it something you want to launch, sync, and close repeatedly? 

How would you like to trigger the sync?  A literal unix signal is tricky because of containers. Something involving the network is easier, but now you have to think about authorization and authentication, and who's allowed to trigger, and how rapidly.

**Comment by thockin** [comment]
Revisiting this - it's true that k8s does not make it easy to send a signal to a running pod, but that's out of scope for git-sync.  I'm closing this for bookkeeping purposes, but happy to discuss if you think you need a different mode of "notification".
